language: node_js
node_js: node
script: yarn listdiff && yarn lint && yarn build

deploy:
    - provider: npm
      edge: true
      on:
          repo: magic-akari/seamless-scroll-polyfill
          branch: master
          tags: true
